Output "demo.gif"

Require echo

Set Shell "zsh"
Set FontSize 24
Set Width 1200
Set Height 600
Set TypingSpeed 50ms
Set FontFamily "Hack Nerd Font"
Set Padding 16
Set WindowBar Colorful
Set Framerate 20

Hide
Type "clear"
Enter
Show

Type `mqt demo.md`
Enter
Sleep 1.5s

Type `:`
Sleep 0.5s

Type `.h`
Sleep 1.5s

Backspace 2
Sleep 1.5s

Type `.code`
Sleep 1.5s

Type `("python")`
Sleep 1.5s

Escape
Sleep 1.5s
